name: Publish Types Package to npmjs

on:
  push:
    tags:
      - 'chat-client-ui-types/v**'

jobs:
  publish:
    uses: ./.github/workflows/publish-to-npm.yaml
    with:
      workspace: 'chat-client-ui-types'
    secrets: inherit